name: Build

on: workflow_dispatch

env:
  registry: ghcr.io

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v3

      - name: buildx installation
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            IMAGE_ALPINE=alpine:3.14.0
          tags: ${{ env.registry }}/${{ github.repository }}:${{ github.sha }}
          push: true
